### ISSUE TITLE
Sync with latest version

### ISSUE THREAD

**Issue by vincentbernat** [MorbZ/Searchonymous#10]
Hey!

On addons.mozilla.org, the extension is updated recently, versioned as 1.0.6 and compatible with Firefox 57. Would it be possible to update this repository?

Thanks!

**Comment by MorbZ** [comment]
The version 1.0.6 for Firefox is exactly the same as the version 1.0.5 for Chrome (chrome directory). I just had to increase the version number in order to update it on the Mozilla page.
