### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by hyperfekt** [MorbZ/Searchonymous#11]
Searchonymous has stopped working just now. I tried a reinstall, but to no avail. Once logged in anywhere with Google I am also logged in on the search page. Maybe others can confirm, my hypothesis is that Google just changed their session cookie.

**Comment by hyperfekt** [comment]
Now it works again - very strange! Must've been some kind of glitch?..

**Comment by MorbZ** [comment]
Just checked and it doesn't seem Google changed their cookies. Maybe Google is doing experiments or some other addon is interfering.

**Comment by t0mk** [comment]
same happened to me
