### ISSUE TITLE
Doesn't work in Google Chrome anymore

### ISSUE THREAD

**Issue by IvoryJam** [MorbZ/Searchonymous#12]
No longer working in Google Chrome Version 72.0.3626.96 (Official Build) (64-bit) on Xubuntu 18.04 4.15.0-45-generic. No errors in console.

**Comment by MorbZ** [comment]
You are right, starting from Chrome 72 an extra option is required to receive the cookie header. I try to update the addon soon.

**Comment by MorbZ** [comment]
Fixed by 88a1e64ccf87cb466632c5e9a98e95f5cb40ea4a
